# Generated by Django 3.1.2 on 2020-10-01 12:46

from django.db import migrations, models
import form.models


def make_surveys(apps, schema_editor):
    Survey = apps.get_model("form", "Survey")
    Survey.objects.create(slug="deadbeef", question="How well did we do?")

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=form.models.make_uuid)),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('comment', models.CharField(max_length=2000)),
            ],
        ),
        migrations.RunPython(make_surveys, reverse_code=lambda apps, schema_editor: None)
    ]
