# Generated by Django 3.1.2 on 2020-10-01 12:51

from django.db import migrations, models
import form.models

def make_factors(apps, schema_editor):
    Factor = apps.get_model("form", "Factor")
    Survey = apps.get_model("form", "Survey")
    survey = Survey.objects.first()
    for title in ["Speed of service", "The agents attitude", "I did not understand the agent"]:
        factor = Factor.objects.create(title=title)
        survey.factors.add(factor)

class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_add_base_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=form.models.make_uuid)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='factors',
            field=models.ManyToManyField(related_name='survey', to='form.Factor'),
        ),
        migrations.AddField(
            model_name='response',
            name='factors',
            field=models.ManyToManyField(related_name='+', to='form.Factor'),
        ),
        migrations.RunPython(make_factors, reverse_code=lambda apps, schema_editor: None)
    ]
